name: starred-repos-organizer

services:
    app:
        image: starred-repos-organizer
        container_name: sro
        build:
            context: .
        volumes:
            - ./user-data.json:/home/node/app/user-data.json
        ports:
            - 3000:3000
            - 5173:5173
        restart: unless-stopped
